export const GET_TOP_ANIME_REQUEST = 'GET_TOP_ANIME_REQUEST';
export const GET_TOP_ANIME_SUCCESS = 'GET_TOP_ANIME_SUCCESS';
export const GET_TOP_ANIME_FAILURE = 'GET_TOP_ANIME_FAILURE';

export const GET_MOVIE_REQUEST = 'GET_MOVIE_REQUEST';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAILURE = 'GET_MOVIE_FAILURE';

export const GET_TOP_MANGA_REQUEST = 'GET_TOP_MANGA_REQUEST';
export const GET_TOP_MANGA_SUCCESS = 'GET_TOP_MANGA_SUCCESS';
export const GET_TOP_MANGA_FAILURE = 'GET_TOP_MANGA_FAILURE';

export const GET_TOP_REVIEWS_REQUEST = 'GET_TOP_REVIEWS_REQUEST';
export const GET_TOP_REVIEWS_SUCCESS = 'GET_TOP_REVIEWS_SUCCESS';
export const GET_TOP_REVIEWS_FAILURE = 'GET_TOP_REVIEWS_FAILURE';

export const GET_ANIME_REQUEST = 'GET_ANIME_REQUEST';
export const GET_ANIME_SUCCESS = 'GET_ANIME_SUCCESS';
export const GET_ANIME_FAILURE = 'GET_ANIME_FAILURE';

export const GET_FULL_ANIME_REQUEST = 'GET_FULL_ANIME_REQUEST';
export const GET_FULL_ANIME_SUCCESS = 'GET_FULL_ANIME_SUCCESS';
export const GET_FULL_ANIME_FAILURE = 'GET_FULL_ANIME_FAILURE';
